### ISSUE TITLE
add combined summary file path on each individual summary xml file

### ISSUE THREAD

**Issue by adamjonas** [bitcoinsearch/summarizer#34]
We use the individual summary paths in the history section of the combined summaries page but one you are on a individual summary, a reader has no context to know which index in the collection they are or whether this individual post belongs to a combined summary.

From an app development perspective it'd be helpful to have a path to the combined summary it belongs to and the index of where it belongs in the history.

**Comment by kouloumos** [comment]
Closing this as it doesn't seem to be an issue anymore.
